apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-services
  namespace: argocd
spec:
  description: "Root application project for managing infra-services components"
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      namespace: 'services-*'  # For all namespaces starting with 'services-'
    - server: '*'
      namespace: 'argocd'  
    - server: '*'
      namespace: 'kube-system'    
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    - group: 'apiextensions.k8s.io'
      kind: 'CustomResourceDefinition'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRole'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRoleBinding'
    - group: 'admissionregistration.k8s.io'
      kind: 'ValidatingWebhookConfiguration'
