apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  project: root-application
  source:
    repoURL: 'https://github.com/dpetrocelli/argocd-apps.git'
    targetRevision: HEAD
    path: services/definitions  # Adjust this path to the actual path in the repository
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
