/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ContactBook } from "./ContactBook";
export * as factories from "./factories";
export { ContactBook__factory } from "./factories/ContactBook__factory";
