apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: le-example-dns
  namespace: whoami
spec:
  acme:
    email: dmpetrocelli@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
