apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: whoami
type: Opaque
stringData:
  api-token: kdJfh7gNJOUt0w3OIJ0SqLibM3IEIB7dQo-eNC-t
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: le-example-dns
  namespace: whoami
spec:
  acme:
    email: dmpetrocelli@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: whoami
  annotations:
    cert-manager.io/issuer: "le-example-dns"
spec:
  tls:
    - hosts:
        - whoami.10.net.ar
      secretName: tls-whoami-ingress-dns
  rules:
    - host: whoami.10.net.ar
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  name: web
