name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

          
          
      - name: Check and Create GCS Bucket
        run: |
          gcloud config set project ${{ secrets.PROJECT_ID }}
          BUCKET_NAME="tf-bucket-store-dev-unlu2024"
          PROJECT_ID=${{ secrets.PROJECT_ID }}
          
          # Check if the bucket exists
          if gsutil ls -p $PROJECT_ID | grep gs://$BUCKET_NAME/; then
            echo "Bucket $BUCKET_NAME already exists."
          else
            echo "Creating bucket $BUCKET_NAME..."
            gsutil mb -p $PROJECT_ID gs://$BUCKET_NAME/
          fi