name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  pipeline1:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
           echo "💡 The ${{ github.repository }} repository has been cloned "
           
           cd SD2024/class5_sobel/dockerimage/nodejs-web-server/dockerimage/nodejs-web-server

           ls -lah 
           echo " HOLA 2"
           

