name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  pipeline1:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          echo "💡 The ${{ github.repository }} repository has been cloned "
          # [S1] nos paramos en la carpeta
          cd SD2024/class5_sobel/dockerimage/nodejs-web-server2
          # [S2] bajar las dependencias
          npm i 
          # [s3] correr npm outdated
          npm outdated
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build local container
        uses: docker/build-push-action@v4
        with:
          context: SD2024/class5_sobel/dockerimage/nodejs-web-server2/
          tags: localbuild/testimage:latest
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"   
           
           

