name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GPC_CREDENTIALS_FILE }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Check and Create GCS Bucket
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          gcloud config set project $PROJECT_ID

          # Check if the bucket exists
          if gsutil ls -p $PROJECT_ID | grep gs://$BUCKET_NAME/; then
            echo "Bucket $BUCKET_NAME already exists."
          else
            echo "Creating bucket $BUCKET_NAME..."
            gsutil mb -p $PROJECT_ID gs://$BUCKET_NAME/
          fi

      - name: Write GCP Credentials to File
        run: |
          echo "$GCP_CREDENTIALS" > gcp-credentials.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GPC_CREDENTIALS_FILE }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.BUCKET_NAME }}" \
            -backend-config="prefix=terraform/state"
        working-directory: SD2024/tif/cloud-shared-services/05-gke_cluster/terraform

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: SD2024/tif/cloud-shared-services/05-gke_cluster/terraform
        env:
          TF_LOG: DEBUG
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
