name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  otro-nombre:
    runs-on: ubuntu-latest
    steps:
      - |
        echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      