name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  otro-nombre:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "Running additional commands..."
          echo " hola desde sistemas distribuidos usando la rama  ${{ github.ref }}"
          # Add your additional commands here
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
           echo "💡 The ${{ github.repository }} repository has been cloned 