name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  otro-nombre:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "Running additional commands..."
          # Add your additional commands here