apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: services
spec:
  project: default
  source:
    repoURL: 'https://github.com/dpetrocelli/unlu2024.git'
    targetRevision: HEAD
    path: SD2024/tif/cloud-shared-services/argocd/services/rabbitmq
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
